version: '3.8'

# Does not come with the NodeJS server...
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data:z"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_LISTEN_PORT: 4321
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - ${PGADMIN_PORT}:4321

  flowise:
      image: flowiseai/flowise
      restart: always
      depends_on:
        - ollama
        - db
      environment:
          - PORT=${FLOWWISE_PORT}
          - FLOWISE_USERNAME=${FLOWISE_USERNAME}
          - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
          - DATABASE_PATH=/root/.flowise
          - APIKEY_PATH=/root/.flowise
          - LOG_PATH=/root/.flowise/logs
          - SECRETKEY_PATH=/root/.flowise
          - BLOB_STORAGE_PATH=/root/.flowise/storage
      volumes:
          - "./flowise_data:/root/.flowise:z"
      ports:
          - '${FLOWWISE_PORT}:${FLOWWISE_PORT}'
      command: /bin/sh -c "sleep 3; flowise start"

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: always
    volumes:
      - "./ollama_data:/root/.ollama:z"
    ports:
      - 11454:11434

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - "./redis_data:/data:z"
