-- AlterTable
ALTER TABLE "LocationLog" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "PhotoLog" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "SMSLog" ALTER COLUMN "timestamp" SET DEFAULT CURRENT_TIMESTAMP;
